language: node_js
node_js:
  - '10'
sudo: required
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
env:
  - ENV=TEST
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install firebase-tools -g
  - npm ci --ignore-scripts
script:
  # run build script specified in package.json
  - npm run ci
  - npm run build:prod
  # call script for deploying of produced artifacts
  # - bash ./.travis-deploy.sh
after_success:
  - firebase deploy --force --project ngx-jsonresume --token $FIREBASE_TOKEN
